<?php 
$collection = $this->getBrands();
$media = $this->getImageMediaPath();
?>
<style>
	.brand-char {
    min-width: 300px;
    float: left;
    min-height: 130px;
}
</style>

<h3>Brands</h3>
<ul class="brands">
<?php foreach($collection as $_fbrand):?>
	<li id="<?php echo $_fbrand->getName(); ?>">
		<?php if($_fbrand->getLogo()):?>
		<div class="brandimage">
			<?php if($_fbrand->getUrlKey()):?>
				<a href="<?php echo $this->getUrl('brand').$_fbrand->getUrlKey()?>">
			<?php else:?>
				<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_fbrand->getId()));?>">
			<?php endif;?>
				<img class="f-barnd-img" src="<?php echo $media.$_fbrand->getLogo() ?>" title="<?php echo $_fbrand->getName();?>" alt="<?php echo $_fbrand->getName();?>" style="height:100px"/>
			</a>
		</div>
		<?php endif;?>
		<div class="brandname">
			<?php if($_fbrand->getUrlKey()):?>
				<a href="<?php echo $this->getUrl('brand').$_fbrand->getUrlKey()?>">
			<?php else:?>
				<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_fbrand->getId()));?>">
			<?php endif;?>
				<?php echo $_fbrand->getName();?>
			</a>
		</div>
		<?php if($_fbrand->getDescription()):?>
		<div class="branddesc">
			<?php echo $_fbrand->getDescription();?>
		</div>
		<?php endif;?>
	</li>
	
<?php endforeach;?>
</div>