<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span class="copyright-left"><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
   <span class="copyright-right"><?= /* @escapeNotVerified */ __('Site By ') ?>
    <strong><a href="http://www.predikkta.com"
       target="_blank">
        <?= /* @escapeNotVerified */ __('Predikkta') ?>
    </a></strong>
    </span>


</small>
