<div>
    <a href="#" id="sizechart">size guide</a>
</div>

<div id="popup-modal" style="display:none;">
    <table class="sizeGrid" border="0">
          <tbody>
          <tr><th colspan="3">Women</th></tr>
          <tr>
          <td>US/Aust</td>
          <td>EURO</td>
          <td>UK</td>
          </tr>
          <tr height="17">
          <td height="17">5</td>
          <td>36</td>
          <td>3</td>
          </tr>
          <tr height="17">
          <td height="17">6</td>
          <td>37</td>
          <td>4</td>
          </tr>
          <tr height="17">
          <td height="17">7</td>
          <td>38</td>
          <td>5</td>
          </tr>
          <tr height="17">
          <td height="17">8</td>
          <td>39</td>
          <td>6</td>
          </tr>
          <tr height="17">
          <td height="17">9</td>
          <td>40</td>
          <td>7</td>
          </tr>
          <tr height="17">
          <td height="17">10</td>
          <td>41</td>
          <td>8</td>
          </tr>
          <tr height="17">
          <td height="17">11</td>
          <td>42</td>
          <td>9</td>
          </tr>
          </tbody>
          </table>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Size Guide Chart',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            $("#sizechart").on('click',function(){ 
                $("#popup-modal").modal("openModal");
            });

        }
    );
</script>